import type { Metadata } from "next";
import "./globals.scss";
import {NextIntlClientProvider} from 'next-intl';
import {getLocale, getMessages} from 'next-intl/server';
import Header from "@/containers/Header";
import Footer from "@/containers/Footer";
import Providers from "./providers";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const locale = await getLocale();
  const messages = await getMessages();

  // const response = await fetch('https://vergilix-backend.vercel.app/api/rates')
  // const data = await response.json()
  // console.log(data)

  return (
    <html lang={locale}>
      <body>
        <NextIntlClientProvider messages={messages}>
          <Providers>
            <Header/>
            {children}
            <Footer/>
          </Providers>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
